precision: float32
device: cpu
experiment_version: 2026-04-09_01-14-06
output_path: ./output
processed_data_path: ./data/processed
plot_plane: true
plot_basis: true
plot_coefficients: true
plot_coefficients_mean: false
percentiles: 3
vectors_to_highlight: 3
